import os
import pandas as pd
import matplotlib.pyplot as plt
import math

df = pd.read_csv('data/resultados.csv')
os.makedirs('data', exist_ok=True)

plt.figure(figsize=(10, 6))
plt.plot(df['Iteracoes'], df['Erro_Absoluto'], marker='o', color='red', linewidth=2, markersize=8)
plt.title('Erro Absoluto na Aproximação de PI (Série de Leibniz)', fontsize=14, fontweight='bold')
plt.xlabel('Número de Iterações')
plt.ylabel('Erro Absoluto')
plt.xscale('log')
plt.yscale('log')
plt.grid(True, linestyle='--', alpha=0.7)
plt.tight_layout()
plt.savefig('data/grafico_erro_absoluto.png')
plt.close()
print("Gráfico gerado com sucesso em 'data/grafico_erro_absoluto.png'!")

plt.figure(figsize=(10, 6))
plt.plot(df['Iteracoes'], df['Tempo'], marker='s', color='blue', linewidth=2, markersize=8)
plt.title('Tempo de Execução vs Número de Iterações', fontsize=14, fontweight='bold')
plt.xlabel('Número de Iterações')
plt.ylabel('Tempo de Execução (Segundos)')
plt.xscale('log')
plt.yscale('log')
plt.grid(True, linestyle='--', alpha=0.7)
plt.tight_layout()
plt.savefig('data/grafico_tempo_execucao.png')
plt.close()
print("Gráfico gerado com sucesso em 'data/grafico_tempo_execucao.png'!")

plt.figure(figsize=(10, 6))
plt.plot(df['Iteracoes'], df['PI_Calculado'], marker='o', color='green', linewidth=2, markersize=8, label='PI Calculado')
plt.axhline(y=math.pi, color='red', linestyle='--', linewidth=2, label=f'PI Real ({math.pi:.10f})')
plt.title('Convergência de PI pela Série de Leibniz', fontsize=14, fontweight='bold')
plt.xlabel('Número de Iterações')
plt.ylabel('Valor de PI')
plt.xscale('log')
plt.grid(True, linestyle='--', alpha=0.7)
plt.legend()
plt.tight_layout()
plt.savefig('data/grafico_convergencia_pi.png')
plt.close()
print("Gráfico gerado com sucesso em 'data/grafico_convergencia_pi.png'!")

fig, axes = plt.subplots(1, 3, figsize=(18, 5))
fig.suptitle('Análise Completa: Cálculo Aproximado de PI por Leibniz', fontsize=16, fontweight='bold')

axes[0].plot(df['Iteracoes'], df['Erro_Absoluto'], marker='o', color='red', linewidth=2)
axes[0].set_title('Erro Absoluto')
axes[0].set_xlabel('Iterações')
axes[0].set_ylabel('Erro')
axes[0].set_xscale('log')
axes[0].set_yscale('log')
axes[0].grid(True, linestyle='--', alpha=0.7)

axes[1].plot(df['Iteracoes'], df['Tempo'], marker='s', color='blue', linewidth=2)
axes[1].set_title('Tempo de Execução')
axes[1].set_xlabel('Iterações')
axes[1].set_ylabel('Tempo (s)')
axes[1].set_xscale('log')
axes[1].set_yscale('log')
axes[1].grid(True, linestyle='--', alpha=0.7)

axes[2].plot(df['Iteracoes'], df['PI_Calculado'], marker='o', color='green', linewidth=2, label='PI Calculado')
axes[2].axhline(y=math.pi, color='red', linestyle='--', linewidth=2, label='PI Real')
axes[2].set_title('Convergência de PI')
axes[2].set_xlabel('Iterações')
axes[2].set_ylabel('Valor de PI')
axes[2].set_xscale('log')
axes[2].grid(True, linestyle='--', alpha=0.7)
axes[2].legend()

plt.tight_layout()
plt.savefig('data/grafico_comparativo.png')
plt.close()
print("Gráfico comparativo gerado com sucesso em 'data/grafico_comparativo.png'!")
